apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<YOU>/<REPO>.git   # <- change this
    targetRevision: main
    path: quiz-app
  destination:
    server: https://kubernetes.default.svc
    namespace: quiz-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true